apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: portifolio-una
  name: portifolio-una
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portifolio-una
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: portifolio-una
    spec:
      containers:
      - image: docker.io/library/node:lts-slim
        name: node
        resources: {}
status: {}
