apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: portifolio-una
  name: portifolio-una
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: portifolio-una
status:
  loadBalancer: {}
