apiVersion: v1
kind: Service
metadata:
  name: portifolio-una
spec:
  type: NodePort
  selector:
    app: portifolio-una
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portifolio-una
spec:
  selector:
    matchLabels:
      app: portifolio-una
  template:
    metadata:
      labels:
        app: portifolio-una
    spec:
      containers:
      - image: docker.io/library/node:lts-slim
        name: node
        args:
        - npm
        - start
        ports:
        - containerPort: 8000
        workingDir: /usr/src/app
        volumeMounts:
        - name: portifolio-una
          mountPath: /usr/src/app
      volumes:
      - name: portifolio-una
        hostPath:
          path: /home/rafael/Projects/gatsby-starter-delog
          type: Directory
